baseURL: https://www.jensandresen.com
languageCode: en-us
title: Comments on Software Development
theme: tale
author:
  name: Jens Andresen
params:
  author: Jens Andresen
menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
    # - identifier: contact
    #   name: Contact
    #   url: /contact/
paginate: 50
